//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeaWeb {
    
    
    /// <summary>
    /// Clase Default.
    /// </summary>
    /// <remarks>
    /// Clase generada automáticamente.
    /// </remarks>
    public partial class Default {
        
        /// <summary>
        /// Control loteRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator loteRequiredFieldValidator;
        
        /// <summary>
        /// Control Id_LoteTextbox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Id_LoteTextbox;
        
        /// <summary>
        /// Control Cuit_CanalTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Cuit_CanalTextBox;
        
        /// <summary>
        /// Control Presta_ServCheckBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox Presta_ServCheckBox;
        
        /// <summary>
        /// Control puntoVentaRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator puntoVentaRequiredFieldValidator;
        
        /// <summary>
        /// Control Punto_VentaTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Punto_VentaTextBox;
        
        /// <summary>
        /// Control GLN_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox GLN_VendedorTextBox;
        
        /// <summary>
        /// Control Codigo_Interno_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Codigo_Interno_VendedorTextBox;
        
        /// <summary>
        /// Control Razon_Social_VendedorRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Razon_Social_VendedorRequiredFieldValidator;
        
        /// <summary>
        /// Control Razon_Social_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Razon_Social_VendedorTextBox;
        
        /// <summary>
        /// Control CUITVendedorRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator CUITVendedorRequiredFieldValidator;
        
        /// <summary>
        /// Control Cuit_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Cuit_VendedorTextBox;
        
        /// <summary>
        /// Control Condicion_IVA_VendedorDropDownList.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Condicion_IVA_VendedorDropDownList;
        
        /// <summary>
        /// Control InicioDeActividadesVendedorDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl InicioDeActividadesVendedorDatePickerWebUserControl;
        
        /// <summary>
        /// Control Contacto_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Contacto_VendedorTextBox;
        
        /// <summary>
        /// Control Domicilio_Calle_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Calle_VendedorTextBox;
        
        /// <summary>
        /// Control Domicilio_Numero_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Numero_VendedorTextBox;
        
        /// <summary>
        /// Control Domicilio_Piso_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Piso_VendedorTextBox;
        
        /// <summary>
        /// Control Domicilio_Depto_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Depto_VendedorTextBox;
        
        /// <summary>
        /// Control Domicilio_Sector_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Sector_VendedorTextBox;
        
        /// <summary>
        /// Control Domicilio_Torre_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Torre_VendedorTextBox;
        
        /// <summary>
        /// Control Domicilio_Manzana_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Manzana_VendedorTextBox;
        
        /// <summary>
        /// Control Localidad_VendedorRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Localidad_VendedorRequiredFieldValidator;
        
        /// <summary>
        /// Control Localidad_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Localidad_VendedorTextBox;
        
        /// <summary>
        /// Control Provincia_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Provincia_VendedorTextBox;
        
        /// <summary>
        /// Control Cp_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Cp_VendedorTextBox;
        
        /// <summary>
        /// Control Email_VendedorRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Email_VendedorRequiredFieldValidator;
        
        /// <summary>
        /// Control Email_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Email_VendedorTextBox;
        
        /// <summary>
        /// Control Telefono_VendedorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Telefono_VendedorTextBox;
        
        /// <summary>
        /// Control GLN_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox GLN_CompradorTextBox;
        
        /// <summary>
        /// Control Codigo_Interno_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Codigo_Interno_CompradorTextBox;
        
        /// <summary>
        /// Control Codigo_Doc_Identificatorio_CompradorDropDownList.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Codigo_Doc_Identificatorio_CompradorDropDownList;
        
        /// <summary>
        /// Control docCompradorRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator docCompradorRequiredFieldValidator;
        
        /// <summary>
        /// Control Nro_Doc_Identificatorio_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Nro_Doc_Identificatorio_CompradorTextBox;
        
        /// <summary>
        /// Control Denominacion_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Denominacion_CompradorTextBox;
        
        /// <summary>
        /// Control Condicion_IVA_CompradorDropDownList.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Condicion_IVA_CompradorDropDownList;
        
        /// <summary>
        /// Control InicioDeActividadesCompradorDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl InicioDeActividadesCompradorDatePickerWebUserControl;
        
        /// <summary>
        /// Control Contacto_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Contacto_CompradorTextBox;
        
        /// <summary>
        /// Control Domicilio_Calle_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Calle_CompradorTextBox;
        
        /// <summary>
        /// Control Domicilio_Numero_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Numero_CompradorTextBox;
        
        /// <summary>
        /// Control Domicilio_Piso_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Piso_CompradorTextBox;
        
        /// <summary>
        /// Control Domicilio_Depto_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Depto_CompradorTextBox;
        
        /// <summary>
        /// Control Domicilio_Sector_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Sector_CompradorTextBox;
        
        /// <summary>
        /// Control Domicilio_Torre_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Torre_CompradorTextBox;
        
        /// <summary>
        /// Control Domicilio_Manzana_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Domicilio_Manzana_CompradorTextBox;
        
        /// <summary>
        /// Control Localidad_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Localidad_CompradorTextBox;
        
        /// <summary>
        /// Control Provincia_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Provincia_CompradorTextBox;
        
        /// <summary>
        /// Control Cp_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Cp_CompradorTextBox;
        
        /// <summary>
        /// Control Email_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Email_CompradorTextBox;
        
        /// <summary>
        /// Control Telefono_CompradorTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Telefono_CompradorTextBox;
        
        /// <summary>
        /// Control Tipo_De_ComprobanteDropDownList.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Tipo_De_ComprobanteDropDownList;
        
        /// <summary>
        /// Control Numero_ComprobanteRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Numero_ComprobanteRequiredFieldValidator;
        
        /// <summary>
        /// Control Numero_ComprobanteTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Numero_ComprobanteTextBox;
        
        /// <summary>
        /// Control FechaEmisionDatePickerRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator FechaEmisionDatePickerRequiredFieldValidator;
        
        /// <summary>
        /// Control FechaEmisionDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl FechaEmisionDatePickerWebUserControl;
        
        /// <summary>
        /// Control FechaVencimientoDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl FechaVencimientoDatePickerWebUserControl;
        
        /// <summary>
        /// Control FechaServDesdeDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl FechaServDesdeDatePickerWebUserControl;
        
        /// <summary>
        /// Control FechaServHastaDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl FechaServHastaDatePickerWebUserControl;
        
        /// <summary>
        /// Control CAETextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox CAETextBox;
        
        /// <summary>
        /// Control FechaCAEVencimientoDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl FechaCAEVencimientoDatePickerWebUserControl;
        
        /// <summary>
        /// Control FechaCAEObtencionDatePickerWebUserControl.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::FeaWeb.DatePickerWebUserControl FechaCAEObtencionDatePickerWebUserControl;
        
        /// <summary>
        /// Control ComentariosTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ComentariosTextBox;
        
        /// <summary>
        /// Control detalleGridView.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView detalleGridView;
        
        /// <summary>
        /// Control Importe_Total_Neto_Gravado_ResumenRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Importe_Total_Neto_Gravado_ResumenRequiredFieldValidator;
        
        /// <summary>
        /// Control Importe_Total_Neto_Gravado_ResumenTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Importe_Total_Neto_Gravado_ResumenTextBox;
        
        /// <summary>
        /// Control Importe_Total_Concepto_No_Gravado_ResumenRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Importe_Total_Concepto_No_Gravado_ResumenRequiredFieldValidator;
        
        /// <summary>
        /// Control Importe_Total_Concepto_No_Gravado_ResumenTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Importe_Total_Concepto_No_Gravado_ResumenTextBox;
        
        /// <summary>
        /// Control Importe_Operaciones_Exentas_ResumenRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Importe_Operaciones_Exentas_ResumenRequiredFieldValidator;
        
        /// <summary>
        /// Control Importe_Operaciones_Exentas_ResumenTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Importe_Operaciones_Exentas_ResumenTextBox;
        
        /// <summary>
        /// Control Impuesto_Liq_ResumenRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Impuesto_Liq_ResumenRequiredFieldValidator;
        
        /// <summary>
        /// Control Impuesto_Liq_ResumenTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Impuesto_Liq_ResumenTextBox;
        
        /// <summary>
        /// Control Impuesto_Liq_Rni_ResumenRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Impuesto_Liq_Rni_ResumenRequiredFieldValidator;
        
        /// <summary>
        /// Control Impuesto_Liq_Rni_ResumenTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Impuesto_Liq_Rni_ResumenTextBox;
        
        /// <summary>
        /// Control Importe_Total_Factura_ResumenRequiredFieldValidator.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator Importe_Total_Factura_ResumenRequiredFieldValidator;
        
        /// <summary>
        /// Control Importe_Total_Factura_ResumenTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Importe_Total_Factura_ResumenTextBox;
        
        /// <summary>
        /// Control Observaciones_ResumenTextBox.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Observaciones_ResumenTextBox;
        
        /// <summary>
        /// Control ValidationSummary1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        
        /// <summary>
        /// Control GenerarButton.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button GenerarButton;
    }
}
