// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.0
// Schema file: LIQ1108.xsd
// Creation Date: 09/11/2011 06:13:58 PM
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace Liq
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class periodo_facturacionCollection : ArrayList
	{
		public periodo_facturacion Add(periodo_facturacion obj)
		{
			base.Add(obj);
			return obj;
		}

		public periodo_facturacion Add()
		{
			return Add(new periodo_facturacion());
		}

		public void Insert(int index, periodo_facturacion obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(periodo_facturacion obj)
		{
			base.Remove(obj);
		}

		new public periodo_facturacion this[int index]
		{
			get { return (periodo_facturacion) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class conceptos_facturacionCollection : ArrayList
	{
		public conceptos_facturacion Add(conceptos_facturacion obj)
		{
			base.Add(obj);
			return obj;
		}

		public conceptos_facturacion Add()
		{
			return Add(new conceptos_facturacion());
		}

		public void Insert(int index, conceptos_facturacion obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(conceptos_facturacion obj)
		{
			base.Remove(obj);
		}

		new public conceptos_facturacion this[int index]
		{
			get { return (conceptos_facturacion) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class contratoCollection : ArrayList
	{
		public contrato Add(contrato obj)
		{
			base.Add(obj);
			return obj;
		}

		public contrato Add()
		{
			return Add(new contrato());
		}

		public void Insert(int index, contrato obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(contrato obj)
		{
			base.Remove(obj);
		}

		new public contrato this[int index]
		{
			get { return (contrato) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class concepto_facturacionCollection : ArrayList
	{
		public concepto_facturacion Add(concepto_facturacion obj)
		{
			base.Add(obj);
			return obj;
		}

		public concepto_facturacion Add()
		{
			return Add(new concepto_facturacion());
		}

		public void Insert(int index, concepto_facturacion obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(concepto_facturacion obj)
		{
			base.Remove(obj);
		}

		new public concepto_facturacion this[int index]
		{
			get { return (concepto_facturacion) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class contratosCollection : ArrayList
	{
		public contratos Add(contratos obj)
		{
			base.Add(obj);
			return obj;
		}

		public contratos Add()
		{
			return Add(new contratos());
		}

		public void Insert(int index, contratos obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(contratos obj)
		{
			base.Remove(obj);
		}

		new public contratos this[int index]
		{
			get { return (contratos) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlRoot(ElementName="periodos_facturacion",IsNullable=false),Serializable]
	public class periodos_facturacion
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return periodo_facturacionCollection.GetEnumerator();
		}

		public periodo_facturacion Add(periodo_facturacion obj)
		{
			return periodo_facturacionCollection.Add(obj);
		}

		[XmlIgnore]
		public periodo_facturacion this[int index]
		{
			get { return (periodo_facturacion) periodo_facturacionCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return periodo_facturacionCollection.Count; }
        }

        public void Clear()
		{
			periodo_facturacionCollection.Clear();
        }

		public periodo_facturacion Remove(int index) 
		{ 
            periodo_facturacion obj = periodo_facturacionCollection[index];
            periodo_facturacionCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            periodo_facturacionCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(periodo_facturacion),ElementName="periodo_facturacion",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public periodo_facturacionCollection __periodo_facturacionCollection;
		
		[XmlIgnore]
		public periodo_facturacionCollection periodo_facturacionCollection
		{
			get
			{
				if (__periodo_facturacionCollection == null) __periodo_facturacionCollection = new periodo_facturacionCollection();
				return __periodo_facturacionCollection;
			}
			set {__periodo_facturacionCollection = value;}
		}

		public periodos_facturacion()
		{
		}
	}


	[XmlType(TypeName="periodo_facturacion"),Serializable]
	public class periodo_facturacion
	{

		[XmlElement(ElementName="fecha_desde",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __fecha_desde;
		
		[XmlIgnore]
		public string fecha_desde
		{ 
			get { return __fecha_desde; }
			set { __fecha_desde = value; }
		}

		[XmlElement(ElementName="fecha_hasta",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __fecha_hasta;
		
		[XmlIgnore]
		public string fecha_hasta
		{ 
			get { return __fecha_hasta; }
			set { __fecha_hasta = value; }
		}

		[XmlElement(Type=typeof(contratos),ElementName="contratos",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public contratosCollection __contratosCollection;
		
		[XmlIgnore]
		public contratosCollection contratosCollection
		{
			get
			{
				if (__contratosCollection == null) __contratosCollection = new contratosCollection();
				return __contratosCollection;
			}
			set {__contratosCollection = value;}
		}

		public periodo_facturacion()
		{
		}
	}


	[XmlType(TypeName="contratos"),Serializable]
	public class contratos
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return contratoCollection.GetEnumerator();
		}

		public contrato Add(contrato obj)
		{
			return contratoCollection.Add(obj);
		}

		[XmlIgnore]
		public contrato this[int index]
		{
			get { return (contrato) contratoCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return contratoCollection.Count; }
        }

        public void Clear()
		{
			contratoCollection.Clear();
        }

		public contrato Remove(int index) 
		{ 
            contrato obj = contratoCollection[index];
            contratoCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            contratoCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(contrato),ElementName="contrato",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public contratoCollection __contratoCollection;
		
		[XmlIgnore]
		public contratoCollection contratoCollection
		{
			get
			{
				if (__contratoCollection == null) __contratoCollection = new contratoCollection();
				return __contratoCollection;
			}
			set {__contratoCollection = value;}
		}

		public contratos()
		{
		}
	}


	[XmlType(TypeName="contrato"),Serializable]
	public class contrato
	{

		[XmlAttribute(AttributeName="mov",DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __mov;
		
		[XmlIgnore]
		public string mov
		{ 
			get { return __mov; }
			set { __mov = value; }
		}

		[XmlElement(ElementName="megid_contrato",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __megid_contrato;
		
		[XmlIgnore]
		public string megid_contrato
		{ 
			get { return __megid_contrato; }
			set { __megid_contrato = value; }
		}

		[XmlElement(ElementName="megid_moneda",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __megid_moneda;
		
		[XmlIgnore]
		public string megid_moneda
		{ 
			get { return __megid_moneda; }
			set { __megid_moneda = value; }
		}

		[XmlElement(Type=typeof(conceptos_facturacion),ElementName="conceptos_facturacion",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public conceptos_facturacionCollection __conceptos_facturacionCollection;
		
		[XmlIgnore]
		public conceptos_facturacionCollection conceptos_facturacionCollection
		{
			get
			{
				if (__conceptos_facturacionCollection == null) __conceptos_facturacionCollection = new conceptos_facturacionCollection();
				return __conceptos_facturacionCollection;
			}
			set {__conceptos_facturacionCollection = value;}
		}

		public contrato()
		{
		}
	}


	[XmlType(TypeName="conceptos_facturacion"),Serializable]
	public class conceptos_facturacion
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return concepto_facturacionCollection.GetEnumerator();
		}

		public concepto_facturacion Add(concepto_facturacion obj)
		{
			return concepto_facturacionCollection.Add(obj);
		}

		[XmlIgnore]
		public concepto_facturacion this[int index]
		{
			get { return (concepto_facturacion) concepto_facturacionCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return concepto_facturacionCollection.Count; }
        }

        public void Clear()
		{
			concepto_facturacionCollection.Clear();
        }

		public concepto_facturacion Remove(int index) 
		{ 
            concepto_facturacion obj = concepto_facturacionCollection[index];
            concepto_facturacionCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            concepto_facturacionCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(concepto_facturacion),ElementName="concepto_facturacion",IsNullable=false)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public concepto_facturacionCollection __concepto_facturacionCollection;
		
		[XmlIgnore]
		public concepto_facturacionCollection concepto_facturacionCollection
		{
			get
			{
				if (__concepto_facturacionCollection == null) __concepto_facturacionCollection = new concepto_facturacionCollection();
				return __concepto_facturacionCollection;
			}
			set {__concepto_facturacionCollection = value;}
		}

		public conceptos_facturacion()
		{
		}
	}


	[XmlType(TypeName="concepto_facturacion"),Serializable]
	public class concepto_facturacion
	{

		[XmlElement(ElementName="megid_concepto_facturacion",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __megid_concepto_facturacion;
		
		[XmlIgnore]
		public string megid_concepto_facturacion
		{ 
			get { return __megid_concepto_facturacion; }
			set { __megid_concepto_facturacion = value; }
		}

		[XmlElement(ElementName="volumen",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __volumen;
		
		[XmlIgnore]
		public string volumen
		{ 
			get { return __volumen; }
			set { __volumen = value; }
		}

		[XmlElement(ElementName="monto",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __monto;
		
		[XmlIgnore]
		public string monto
		{ 
			get { return __monto; }
			set { __monto = value; }
		}

		[XmlElement(ElementName="megid_tipo_medicion",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __megid_tipo_medicion;
		
		[XmlIgnore]
		public string megid_tipo_medicion
		{ 
			get { return __megid_tipo_medicion; }
			set { __megid_tipo_medicion = value; }
		}

		[XmlElement(ElementName="megid_entidad_medidora",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __megid_entidad_medidora;
		
		[XmlIgnore]
		public string megid_entidad_medidora
		{ 
			get { return __megid_entidad_medidora; }
			set { __megid_entidad_medidora = value; }
		}

		[XmlElement(ElementName="megid_ruta",IsNullable=false,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __megid_ruta;
		
		[XmlIgnore]
		public string megid_ruta
		{ 
			get { return __megid_ruta; }
			set { __megid_ruta = value; }
		}

		public concepto_facturacion()
		{
		}
	}
}
