//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CedeiraAJAX.Facturacion.Electronica {
    
    
    /// <summary>
    /// Clase Permisos.
    /// </summary>
    /// <remarks>
    /// Clase generada automáticamente.
    /// </remarks>
    public partial class Permisos {
        
        /// <summary>
        /// Control permisosUpdatePanel.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel permisosUpdatePanel;
        
        /// <summary>
        /// Control permisosGridView.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView permisosGridView;
        
        /// <summary>
        /// Control permisosUpdateProgress.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress permisosUpdateProgress;
        
        /// <summary>
        /// Control PermisosEditValidationSummary.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary PermisosEditValidationSummary;
        
        /// <summary>
        /// Control PermisosFooterValidationSummary.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary PermisosFooterValidationSummary;
    }
}
